// Mocks generated by Mockito 5.4.2 from annotations
// in safqah_assessment/test/features/expenses_list/data/repositories/expenses_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:safqah_assessment/features/expenses_list/data/data_sources/expenses_local_data_source.dart'
    as _i2;
import 'package:safqah_assessment/features/expenses_list/data/models/expense_item_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExpensesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpensesLocalDataSource extends _i1.Mock
    implements _i2.ExpensesLocalDataSource {
  @override
  _i3.Future<List<_i4.ExpenseItemModel>> getAllExpenses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllExpenses,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ExpenseItemModel>>.value(
            <_i4.ExpenseItemModel>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.ExpenseItemModel>>.value(
            <_i4.ExpenseItemModel>[]),
      ) as _i3.Future<List<_i4.ExpenseItemModel>>);

  @override
  _i3.Future<int> deleteExpense(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExpense,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> addExpense(_i4.ExpenseItemModel? item) => (super.noSuchMethod(
        Invocation.method(
          #addExpense,
          [item],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateExpense(_i4.ExpenseItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExpense,
          [item],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
